spring:
  datasource:
    url: jdbc:h2:mem:egl
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console


# Feign Client Configuration
feign:
  api:
    hg-brasil:
      url: "https://api.hgbrasil.com/"
    chuck-norris:
      url: "https://api.chucknorris.io/"
    the-cat-api:
        url: "https://api.thecatapi.com"
